from arranger_core.ai.artifact_importer import ArtifactImporter, ImportedModelArtifact
from arranger_core.ai.artifact_store import ArtifactStore
from arranger_core.ai.validation_gate import ValidationGate
from arranger_core.ai_generators import AIWalkingBassGenerator
from arranger_core.bass_engine import (
    BASS_ENGINE_VERSION,
    BassAiBackend,
    BassEngine,
    BassEngineMode,
    BassLineLedger,
    BassLineLedgerEntry,
    BassLineStyle,
    BassValidationReport,
)
from arranger_core.catalogs import (
    Ensemble,
    Instrument,
    InstrumentCatalog,
    PatternLibrary,
    ProgressionLibrary,
    ProgressionTemplate,
    ScaleCatalog,
    StyleProfile,
    StyleProfileCatalog,
)
from arranger_core.chords import ChordParser, ParsedChord
from arranger_core.config_loader import MusicConfigLoader, find_repo_root, load_yaml_file
from arranger_core.exporters import (
    export_project,
    find_musescore_cli,
    write_full_midi,
    write_musicxml_score,
    write_track_midi,
)
from arranger_core.harmony_engine import (
    HarmonyFormEngine,
    HarmonyPlan,
    KeyContext,
    degree_to_chord_symbol,
    generate_harmony_plan,
    generate_harmony_project,
    parse_key,
)
from arranger_core.lead_sheet import (
    LeadSheetGenerator,
    MelodyRange,
    generate_lead_sheet_project,
)
from arranger_core.melody_engine import (
    MELODY_ENGINE_VERSION,
    MelodyAiInfillBackend,
    MelodyEngine,
    MelodyEngineMode,
    MelodyValidationReport,
    MotifLedger,
    MotifLedgerEntry,
)
from arranger_core.merge.model_artifact_merger import ProjectMerger
from arranger_core.model_contract import (
    MODEL_CONTRACT_VERSION,
    DeterministicWalkingBassBackend,
    ModelBackend,
    ModelContractModel,
    ModelNote,
    ModelRequest,
    ModelResponse,
    RoleModelGenerator,
    note_token,
    parse_note_token,
)
from arranger_core.music_theory import (
    interval_to_note_name,
    interval_to_pitch_class,
    midi_to_note,
    note_to_midi,
    pitch_class,
    pitch_class_name,
    transpose_note,
)
from arranger_core.performance import (
    PERFORMANCE_MAP_VERSION,
    PerformanceMap,
    PerformanceMapper,
    VelocityRange,
    build_performance_map,
)
from arranger_core.planning import (
    GenerationStrategy,
    LlmPlanner,
    LlmPlannerResult,
    LlmSectionPatch,
    LlmSongPlanPatch,
    PlanAttempt,
    PlanValidator,
    RoleIntent,
)
from arranger_core.presets import EvaluationPrompt, GenerationPreset, PresetLibrary
from arranger_core.prompt_compiler import (
    CompileDefaults,
    PromptCompiler,
    compile_prompt,
    normalize_prompt,
)
from arranger_core.role_generators import (
    DrumsGenerator,
    GenerationContext,
    HornResponseGenerator,
    Humanizer,
    MelodyGenerator,
    PianoCompingGenerator,
    RuleBasedArranger,
    ShoutChorusGenerator,
    WalkingBassGenerator,
    generate_arrangement,
)
from arranger_core.schema import (
    ArrangementProject,
    Bar,
    BarDurationIssue,
    BarDurationValidationError,
    ChordSymbol,
    GenerationSpec,
    KeyMark,
    MeterMark,
    NoteEvent,
    RestEvent,
    SchemaVersionError,
    Section,
    TempoMark,
    Track,
    load_project_json,
    meter_to_quarter_beats,
    project_from_mapping,
    project_to_mapping,
    save_project_json,
)
from arranger_core.sketches import (
    SketchImportError,
    SketchImportResult,
    SketchTrackClassification,
    Text2MidiSketchImporter,
)
from arranger_core.song_planner import (
    SONG_PLAN_VERSION,
    EnergyPoint,
    GrooveMap,
    PhrasePlan,
    SectionPlan,
    SongPlan,
    SongPlanner,
    generate_song_plan,
)
from arranger_core.takes.manager import TakeManager
from arranger_core.takes.models import ArrangementTake, ModelArtifactRecord
from arranger_core.validators import (
    MusicValidationError,
    merge_validation_reports,
    validate_export_package,
    validate_project,
    write_validation_html,
    write_validation_json,
)

__version__ = "0.1.0"

__all__ = [
    "AIWalkingBassGenerator",
    "ArrangementProject",
    "ArrangementTake",
    "ArtifactImporter",
    "ArtifactStore",
    "Bar",
    "BarDurationIssue",
    "BarDurationValidationError",
    "BASS_ENGINE_VERSION",
    "BassAiBackend",
    "BassEngine",
    "BassEngineMode",
    "BassLineLedger",
    "BassLineLedgerEntry",
    "BassLineStyle",
    "BassValidationReport",
    "ChordSymbol",
    "GenerationSpec",
    "GenerationStrategy",
    "GrooveMap",
    "HarmonyFormEngine",
    "HarmonyPlan",
    "KeyMark",
    "KeyContext",
    "LeadSheetGenerator",
    "LlmPlanner",
    "LlmPlannerResult",
    "LlmSectionPatch",
    "LlmSongPlanPatch",
    "MODEL_CONTRACT_VERSION",
    "MELODY_ENGINE_VERSION",
    "MelodyAiInfillBackend",
    "MelodyEngine",
    "MelodyEngineMode",
    "MelodyGenerator",
    "MelodyRange",
    "MelodyValidationReport",
    "MeterMark",
    "ModelBackend",
    "ModelArtifactRecord",
    "ModelContractModel",
    "ModelNote",
    "ModelRequest",
    "ModelResponse",
    "MotifLedger",
    "MotifLedgerEntry",
    "NoteEvent",
    "RestEvent",
    "RoleIntent",
    "RoleModelGenerator",
    "SONG_PLAN_VERSION",
    "SchemaVersionError",
    "Section",
    "SectionPlan",
    "SketchImportError",
    "SketchImportResult",
    "SketchTrackClassification",
    "SongPlan",
    "SongPlanner",
    "TempoMark",
    "Track",
    "TakeManager",
    "Text2MidiSketchImporter",
    "WalkingBassGenerator",
    "__version__",
    "ChordParser",
    "CompileDefaults",
    "DrumsGenerator",
    "DeterministicWalkingBassBackend",
    "EnergyPoint",
    "Ensemble",
    "EvaluationPrompt",
    "GenerationContext",
    "GenerationPreset",
    "HornResponseGenerator",
    "Humanizer",
    "Instrument",
    "InstrumentCatalog",
    "ImportedModelArtifact",
    "MusicConfigLoader",
    "MusicValidationError",
    "ParsedChord",
    "PatternLibrary",
    "PERFORMANCE_MAP_VERSION",
    "PerformanceMap",
    "PerformanceMapper",
    "PhrasePlan",
    "PlanAttempt",
    "PlanValidator",
    "PianoCompingGenerator",
    "PromptCompiler",
    "ProjectMerger",
    "PresetLibrary",
    "ProgressionLibrary",
    "ProgressionTemplate",
    "RuleBasedArranger",
    "ScaleCatalog",
    "ShoutChorusGenerator",
    "StyleProfile",
    "StyleProfileCatalog",
    "compile_prompt",
    "degree_to_chord_symbol",
    "export_project",
    "find_repo_root",
    "find_musescore_cli",
    "generate_arrangement",
    "generate_harmony_plan",
    "generate_harmony_project",
    "generate_lead_sheet_project",
    "generate_song_plan",
    "interval_to_note_name",
    "interval_to_pitch_class",
    "load_project_json",
    "load_yaml_file",
    "merge_validation_reports",
    "midi_to_note",
    "meter_to_quarter_beats",
    "normalize_prompt",
    "note_to_midi",
    "note_token",
    "pitch_class",
    "pitch_class_name",
    "parse_key",
    "parse_note_token",
    "project_from_mapping",
    "project_to_mapping",
    "save_project_json",
    "transpose_note",
    "validate_export_package",
    "validate_project",
    "ValidationGate",
    "VelocityRange",
    "write_full_midi",
    "write_musicxml_score",
    "write_validation_html",
    "write_validation_json",
    "write_track_midi",
    "build_performance_map",
]
